dist: bionic
language: python
python:
    - 3.6
node_js:
    - 14
before_install:
    - scripts/ci-setup.sh
install:
    - sudo python3 -m pip install -r ajenti-core/requirements.txt
script:
    - scripts/ci.sh
addons:
  apt:
    packages:
    - python3-lxml
    - python3-dbus
    - python3-lxml
    - python3-pip
    - libaugeas-dev
    - augeas-tools
cache:
  directories:
    - node_modules
    - $HOME/.cache/pip
    - $HOME/virtualenv
