language: python
python:
    - 2.7
node_js:
    - 0.10
before_script:
    - npm install -g bower
    - pip install ajenti-dev-multitool
    - ajenti-dev-multitool --bower install
    - cd tests
    - npm install
    - cd ..
script:
    - cd tests
    -  ./node_modules/.bin/karma start karma.conf.coffee --single-run
    - cd ..
