language: python
python:
    - 2.7
node_js:
    - 0.10
install:
    - pip install -r ajenti-core/requirements.txt
before_script:
    - npm install -g bower
    - pip install ajenti-dev-multitool
    - ajenti-dev-multitool --bower install
    - cd tests-karma
    - npm install
    - cd ..
script:
    - cd tests-karma
    -  ./node_modules/.bin/karma start karma.conf.coffee --single-run
    - cat coverage/coverage.txt
    - cd ..
