auth:
  allow_sudo: true
  emails: {}
  provider: os
  user_config: os
  users_file: /etc/ajenti/users.yml
bind:
  host: 0.0.0.0
  mode: tcp
  port: 8000
color: default
max_sessions: 9
name: ubuntu-python
session_max_time: 3600
ssl:
  certificate:
  client_auth:
    certificates: []
    enable: false
    force: false
  enable: false
  fqdn_certificate: null
